name = "BinaryRobustOptimization"
uuid = "852f9ff4-52b0-4761-884b-231e0bc23aaa"
authors = ["MathisAzema <az_mathis@orange.fr>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
UnitCommitment = "64606440-39ea-11e9-0f29-3303a1d3d877"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
Distributions = "0.25.120"
Gurobi = "1.7.4"
JuMP = "1.26.0"
MosekTools = "0.15.9"
NCDatasets = "0.14.8"
Plots = "1.40.13"
PyPlot = "2.11.6"
Random = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.6"
TimerOutputs = "0.5.29"
UnitCommitment = "0.4.0"
XLSX = "0.10.4"
